-- ─────────────────────────────────────────────────────────────────────────
-- Seed: guest list from Prita's invitation list
-- Safe to run multiple times — ON CONFLICT (slug) DO NOTHING skips dupes.
-- ─────────────────────────────────────────────────────────────────────────

INSERT INTO guests (name, slug) VALUES
  ('Dimas Pandu',                        'dimas-pandu'),
  ('Salini Rengganis',                   'salini-rengganis'),
  ('Satya Winnie',                       'satya-winnie'),
  ('David John Schaap',                  'david-john-schaap'),
  ('Intan Audia & Partner',              'intan-audia-partner'),
  ('Damaresty Andyani & Partner',        'damaresty-andyani-partner'),
  ('Fauzan Al Habibie',                  'fauzan-al-habibie'),
  ('Guruh Wiratama',                     'guruh-wiratama'),
  ('Bimo Hendarto',                      'bimo-hendarto'),
  ('Achmad Fajar Rydwan & Partner',      'achmad-fajar-rydwan-partner'),
  ('Teh Evi & Partner',                  'teh-evi-partner'),
  ('Alzeina Nysa & Partner',             'alzeina-nysa-partner'),
  ('Bariq Rizki',                        'bariq-rizki'),
  ('M Farid Imansyah & Partner',         'm-farid-imansyah-partner'),
  ('Lenny Kurniawan',                    'lenny-kurniawan'),
  ('Firyal Raudya Yasmin & Partner',     'firyal-raudya-yasmin-partner'),
  ('Dinda Aurelia & Partner',            'dinda-aurelia-partner'),
  ('Nadya Rheinata & Partner',           'nadya-rheinata-partner'),
  ('Nailah Rahmah',                      'nailah-rahmah'),
  ('Nurnahdiyah',                        'nurnahdiyah'),
  ('Nada Djulaeny',                      'nada-djulaeny'),
  ('Kak Dyhar & Partner',                'kak-dyhar-partner'),
  ('Dimas Proklamahari & Partner',       'dimas-proklamahari-partner'),
  ('Indriyani',                          'indriyani'),
  ('Chrysant Jacob & Partner',           'chrysant-jacob-partner'),
  ('Anggun Valentania',                  'anggun-valentania'),
  ('Ira Puspita',                        'ira-puspita'),
  ('Nadira Muharam',                     'nadira-muharam'),
  ('Annisa Azzara',                      'annisa-azzara'),
  ('Risalatul H Anasha',                 'risalatul-h-anasha'),
  ('Riska',                              'riska'),
  ('Deisy Kristianty Handayani',         'deisy-kristianty-handayani'),
  ('Indah Permatasari & Partner',        'indah-permatasari-partner'),
  ('Stephanus Bayu & Partner',           'stephanus-bayu-partner'),
  ('Ismail Saleh & Partner',             'ismail-saleh-partner'),
  ('Ibu Healthy Nirmalasari & Partner',  'ibu-healthy-nirmalasari-partner'),
  ('Bpk. Herwan Abdul Muhyi & Partner',  'bpk-herwan-abdul-muhyi-partner'),
  ('Ibu Dian Fitriyani & Partner',       'ibu-dian-fitriyani-partner'),
  ('Nindya Vinya Lorenz & Partner',      'nindya-vinya-lorenz-partner'),
  ('Alya Dalila & Partner',              'alya-dalila-partner'),
  ('Ditri Indah',                        'ditri-indah'),
  ('Rheny Trie Oktania & Partner',       'rheny-trie-oktania-partner'),
  ('Charvia Ismi Zahrani & Partner',     'charvia-ismi-zahrani-partner'),
  ('Puti Nur Illahirahma',               'puti-nur-illahirahma'),
  ('Rizka Elfira & Partner',             'rizka-elfira-partner'),
  ('Vrescafelthya Trimantari',           'vrescafelthya-trimantari'),
  ('Vina Ramadhani',                     'vina-ramadhani'),
  ('Tara Hanifa',                        'tara-hanifa'),
  ('Indah Permatasari',                  'indah-permatasari'),
  ('Ajiziah Qotrunnada',                 'ajiziah-qotrunnada'),
  ('Om Anto & Tante Neil',               'om-anto-tante-neil'),
  ('Nadia Nunlehu & Family',             'nadia-nunlehu-family'),
  ('Salsabila Sukayana Puteri',          'salsabila-sukayana-puteri'),
  ('Maghfira Addini & Partner',          'maghfira-addini-partner'),
  ('Gita Ramadhani & Partner',           'gita-ramadhani-partner'),
  ('Lailizzah Hani',                     'lailizzah-hani'),
  ('Farah Yumna & Partner',              'farah-yumna-partner'),
  ('Dindi Claudia',                      'dindi-claudia'),
  ('Nurrahmi Wibawani',                  'nurrahmi-wibawani'),
  ('Janna Alila Timur & Partner',        'janna-alila-timur-partner'),
  ('Alief Firmansyah & Partner',         'alief-firmansyah-partner'),
  ('Ainiyah Mutia & Partner',            'ainiyah-mutia-partner'),
  ('Alam Pandji & Partner',              'alam-pandji-partner'),
  ('Alvin Fajri & Partner',              'alvin-fajri-partner'),
  ('Annisa Fitriani & Partner',          'annisa-fitriani-partner'),
  ('R. Bagas Priyotomo & Partner',       'r-bagas-priyotomo-partner'),
  ('Febe Eunike & Partner',              'febe-eunike-partner'),
  ('Hanni Gustyasari',                   'hanni-gustyasari'),
  ('Ikhsantiko Aswianto',                'ikhsantiko-aswianto'),
  ('Kasamira Amadea & Partner',          'kasamira-amadea-partner'),
  ('Merry Puspitasari & Partner',        'merry-puspitasari-partner'),
  ('Raihan Al Muzzamil',                 'raihan-al-muzzamil'),
  ('Raka Ryan & Partner',                'raka-ryan-partner'),
  ('Rizvan Deary & Partner',             'rizvan-deary-partner'),
  ('Saffanati Rahmah',                   'saffanati-rahmah'),
  ('Sultan Rafif & Partner',             'sultan-rafif-partner'),
  ('Suharsa Ary',                        'suharsa-ary'),
  ('Rifky Pratama & Partner',            'rifky-pratama-partner'),
  ('Hafiyan Pragiwaksono & Partner',     'hafiyan-pragiwaksono-partner'),
  ('Amelia Rahmatillah & Partner',       'amelia-rahmatillah-partner'),
  ('Nabil Fadhillah & Partner',          'nabil-fadhillah-partner'),
  ('Syafira Rahma & Partner',            'syafira-rahma-partner'),
  ('Pakde Anton & Bude Sofi',            'pakde-anton-bude-sofi'),
  ('Wyanet Putri',                       'wyanet-putri'),
  ('Erica Annisa',                       'erica-annisa'),
  ('Vini Velolita',                      'vini-velolita'),
  ('Evan Aldiano & Partner',             'evan-aldiano-partner'),
  ('Eunike Callista & Andrew',           'eunike-callista-andrew'),
  ('Juvensius',                          'juvensius'),
  ('Wandy Fernanda',                     'wandy-fernanda'),
  ('Mohammad Akmal',                     'mohammad-akmal')
ON CONFLICT (slug) DO NOTHING;
