INSERT INTO guests (name, slug, source, phone)
SELECT name, slug, source, phone FROM (
    VALUES
    ('Dimas Pandu', 'dimas-pandu', 'Prita', '085158853078'),
    ('Salini Rengganis', 'salini-rengganis', 'Prita', NULL),
    ('Satya Winnie', 'satya-winnie', 'Prita', NULL),
    ('David John Schaap', 'david-john-schaap', 'Prita', NULL),
    ('Intan Audia & Partner', 'intan-audia-partner', 'Prita', NULL),
    ('Damaresty Andyani & Partner', 'damaresty-andyani-partner', 'Prita', NULL),
    ('Fauzan Al Habibie', 'fauzan-al-habibie', 'Prita', NULL),
    ('Guruh Wiratama', 'guruh-wiratama', 'Prita', NULL),
    ('Bimo Hendarto', 'bimo-hendarto', 'Prita', NULL),
    ('Achmad Fajar Rydwan & Partner', 'achmad-fajar-rydwan-partner', 'Prita', NULL),
    ('Teh Evi & Partner', 'teh-evi-partner', 'Prita', NULL),
    ('Alzeina Nysa & Partner', 'alzeina-nysa-partner', 'Prita', NULL),
    ('Bariq Rizki', 'bariq-rizki', 'Prita', NULL),
    ('M Farid Imansyah & Partner', 'm-farid-imansyah-partner', 'Prita', NULL),
    ('Lenny Kurniawan', 'lenny-kurniawan', 'Prita', NULL),
    ('Firyal Raudya Yasmin & Partner', 'firyal-raudya-yasmin-partner', 'Prita', NULL),
    ('Dinda Aurelia & Partner', 'dinda-aurelia-partner', 'Prita', NULL),
    ('Nadya Rheinata & Partner', 'nadya-rheinata-partner', 'Prita', NULL),
    ('Nailah Rahmah', 'nailah-rahmah', 'Prita', NULL),
    ('Nurnahdiyah', 'nurnahdiyah', 'Prita', NULL),
    ('Nada Djulaeny', 'nada-djulaeny', 'Prita', NULL),
    ('Kak Dyhar & Partner', 'kak-dyhar-partner', 'Prita', NULL),
    ('Dimas Proklamahari & Partner', 'dimas-proklamahari-partner', 'Prita', NULL),
    ('Indriyani', 'indriyani', 'Prita', NULL),
    ('Chrysant Jacob & Partner', 'chrysant-jacob-partner', 'Prita', NULL),
    ('Anggun Valentania', 'anggun-valentania', 'Prita', NULL),
    ('Ira Puspita', 'ira-puspita', 'Prita', NULL),
    ('Nadira Muharam', 'nadira-muharam', 'Prita', NULL),
    ('Annisa Azzara', 'annisa-azzara', 'Prita', NULL),
    ('Risalatul H Anasha', 'risalatul-h-anasha', 'Prita', NULL),
    ('Riska', 'riska', 'Prita', NULL),
    ('Deisy Kristianty Handayani', 'deisy-kristianty-handayani', 'Prita', NULL),
    ('Indah Permatasari & Partner', 'indah-permatasari-partner', 'Prita', NULL),
    ('Stephanus Bayu & Partner', 'stephanus-bayu-partner', 'Prita', NULL),
    ('Ismail Saleh & Partner', 'ismail-saleh-partner', 'Prita', NULL),
    ('Ibu Healthy Nirmalasari & Partner', 'ibu-healthy-nirmalasari-partner', 'Prita', NULL),
    ('Bpk. Herwan Abdul Muhyi & Partner', 'bpk-herwan-abdul-muhyi-partner', 'Prita', NULL),
    ('Ibu Dian Fitriyani & Partner', 'ibu-dian-fitriyani-partner', 'Prita', NULL),
    ('Nindya Vinya Lorenz & Partner', 'nindya-vinya-lorenz-partner', 'Prita', NULL),
    ('Alya Dalila & Partner', 'alya-dalila-partner', 'Prita', NULL),
    ('Ditri Indah', 'ditri-indah', 'Prita', NULL),
    ('Rheny Trie Oktania & Partner', 'rheny-trie-oktania-partner', 'Prita', NULL),
    ('Charvia Ismi Zahrani & Partner', 'charvia-ismi-zahrani-partner', 'Prita', NULL),
    ('Puti Nur Illahirahma', 'puti-nur-illahirahma', 'Prita', NULL),
    ('Rizka Elfira & Partner', 'rizka-elfira-partner', 'Prita', NULL),
    ('Vrescafelthya Trimantari', 'vrescafelthya-trimantari', 'Prita', NULL),
    ('Vina Ramadhani', 'vina-ramadhani', 'Prita', NULL),
    ('Tara Hanifa', 'tara-hanifa', 'Prita', NULL),
    ('Indah Permatasari', 'indah-permatasari', 'Prita', NULL),
    ('Ajiziah Qotrunada', 'ajiziah-qotrunada', 'Prita', NULL),
    ('Om Anto & Tante Neil', 'om-anto-tante-neil', 'Prita', NULL),
    ('Nadia Nunlehu & Family', 'nadia-nunlehu-family', 'Prita', NULL),
    ('Salsabila Sukayana Puteri', 'salsabila-sukayana-puteri', 'Prita', NULL),
    ('Maghfira Addini & Partner', 'maghfira-addini-partner', 'Prita', NULL),
    ('Gita Ramadhani & Partner', 'gita-ramadhani-partner', 'Prita', NULL),
    ('Lailizzah Hani', 'lailizzah-hani', 'Prita', NULL),
    ('Farah Yumna & Partner', 'farah-yumna-partner', 'Prita', NULL),
    ('Dindi Claudia', 'dindi-claudia', 'Prita', NULL),
    ('Nurrahmi Wibawani', 'nurrahmi-wibawani', 'Prita', NULL),
    ('Janna Alila Timur & Partner', 'janna-alila-timur-partner', 'Prita', NULL),
    ('Alief Firmansyah & Partner', 'alief-firmansyah-partner', 'Prita', NULL),
    ('Ainiyah Mutia & Partner', 'ainiyah-mutia-partner', 'Prita', NULL),
    ('Alam Pandji & Partner', 'alam-pandji-partner', 'Prita', NULL),
    ('Alvin Fajri & Partner', 'alvin-fajri-partner', 'Prita', NULL),
    ('Annisa Fitriani & Partner', 'annisa-fitriani-partner', 'Prita', NULL),
    ('R. Bagas Priyotomo & Partner', 'r-bagas-priyotomo-partner', 'Prita', NULL),
    ('Febe Eunike & Partner', 'febe-eunike-partner', 'Prita', NULL),
    ('Hanni Gustyasari', 'hanni-gustyasari', 'Prita', NULL),
    ('Ikhsantiko Aswianto', 'ikhsantiko-aswianto', 'Prita', NULL),
    ('Kasamira Amadea & Partner', 'kasamira-amadea-partner', 'Prita', NULL),
    ('Merry Puspitasari & Partner', 'merry-puspitasari-partner', 'Prita', NULL),
    ('Raihan Al Muzzamil', 'raihan-al-muzzamil', 'Prita', NULL),
    ('Raka Ryan & Partner', 'raka-ryan-partner', 'Prita', NULL),
    ('Rizvan Deary & Partner', 'rizvan-deary-partner', 'Prita', NULL),
    ('Saffanati Rahmah', 'saffanati-rahmah', 'Prita', NULL),
    ('Sultan Rafif & Partner', 'sultan-rafif-partner', 'Prita', NULL),
    ('Suharsa Ary', 'suharsa-ary', 'Prita', NULL),
    ('Rifky Pratama & Partner', 'rifky-pratama-partner', 'Prita', NULL),
    ('Amelia Rahmatillah & Partner', 'amelia-rahmatillah-partner', 'Prita', NULL),
    ('Nabil Fadhillah & Partner', 'nabil-fadhillah-partner', 'Prita', NULL),
    ('Syafira Rahma & Partner', 'syafira-rahma-partner', 'Prita', NULL),
    ('Pakde Anton & Bude Sofi', 'pakde-anton-bude-sofi', 'Prita', NULL),
    ('Wyanet Putri', 'wyanet-putri', 'Prita', NULL),
    ('Erica Annisa', 'erica-annisa', 'Prita', NULL),
    ('Vini Velolita', 'vini-velolita', 'Prita', NULL),
    ('Evan Aldiano & Partner', 'evan-aldiano-partner', 'Prita', NULL),
    ('Eunike Callista & Andrew', 'eunike-callista-andrew', 'Prita', NULL),
    ('Juvensius', 'juvensius', 'Prita', NULL),
    ('Wandy Fernanda', 'wandy-fernanda', 'Prita', NULL),
    ('Mohammad Akmal', 'mohammad-akmal', 'Prita', NULL),
    ('Tante Een & Om Dimas', 'tante-een-om-dimas', 'Prita', NULL),
    ('Kak Bunga & Kak Mega', 'kak-bunga-kak-mega', 'Prita', NULL),
    ('Om Ritman & Tante Eny Ratnawati', 'om-ritman-tante-eny-ratnawati', 'Prita', NULL),
    ('Om Rudy Zamrudin & Tante Dian Kurniati', 'om-rudy-zamrudin-tante-dian-kurniati', 'Prita', NULL),
    ('Om Sudjud Siradjuddin & Tante Syawliyanti', 'om-sudjud-siradjuddin-tante-syawliyanti', 'Prita', NULL),
    ('Om Ben Helmi & Tante Susilastri', 'om-ben-helmi-tante-susilastri', 'Prita', NULL),
    ('Om Uus Rukmantara & Tante Linda Ayu T', 'om-uus-rukmantara-tante-linda-ayu-t', 'Prita', NULL),
    ('Om Sapril & Tante Tintin Yunarsih', 'om-sapril-tante-tintin-yunarsih', 'Prita', NULL),
    ('Om Indrawan & Tante Trinyati', 'om-indrawan-tante-trinyati', 'Prita', NULL),
    ('Tante Nurhayati', 'tante-nurhayati', 'Prita', NULL),
    ('Om Jamalulael & Tante Azizah', 'om-jamalulael-tante-azizah', 'Prita', NULL)
) AS v(name, slug, source, phone)
WHERE NOT EXISTS (
    SELECT 1 FROM guests g WHERE g.slug = v.slug
);
