INSERT INTO guests (name, slug, source, phone)
SELECT name, slug, source, phone FROM (
    VALUES
    ('Keluarga Bpk. Ir. Moelyadi', 'keluarga-bpk-ir-moelyadi', 'Tante Dian', NULL),
    ('Keluarga Bpk. Dr. Koesmadi', 'keluarga-bpk-dr-koesmadi', 'Tante Dian', NULL),
    ('Keluarga Bpk. Ir. Wahyudi', 'keluarga-bpk-ir-wahyudi', 'Tante Dian', NULL),
    ('Keluarga Bpk. Arzil Pamuntjak', 'keluarga-bpk-arzil-pamuntjak', 'Tante Dian', NULL),
    ('Keluarga Bpk. Kardjani Chamid', 'keluarga-bpk-kardjani-chamid', 'Tante Dian', NULL),
    ('Bpk. Nur Hakim Arif & Istri', 'bpk-nur-hakim-arif-istri', 'Tante Dian', NULL),
    ('Bpk. Aat Adibirawan & Istri', 'bpk-aat-adibirawan-istri', 'Tante Dian', NULL),
    ('Keluarga (Alm) Bpk. Eddy Suwignyo', 'keluarga-alm-bpk-eddy-suwignyo', 'Tante Dian', NULL),
    ('Keluarga (Alm) Bpk. Atang Ruwinda', 'keluarga-alm-bpk-atang-ruwinda', 'Tante Dian', NULL),
    ('Bpk. Saleh Effendi & Istri', 'bpk-saleh-effendi-istri', 'Tante Dian', NULL),
    ('Bpk. Tedi Kurniadi & Istri', 'bpk-tedi-kurniadi-istri', 'Tante Dian', NULL),
    ('Bpk. Adjie Rustam Ramdja & Istri', 'bpk-adjie-rustam-ramdja-istri', 'Tante Dian', NULL),
    ('Bpk. Agus Soerarso & Istri', 'bpk-agus-soerarso-istri', 'Tante Dian', NULL),
    ('Bpk. Wawan Kadarusman & Istri', 'bpk-wawan-kadarusman-istri', 'Tante Dian', NULL),
    ('Ibu Pengky & Ibu Tutie', 'ibu-pengky-ibu-tutie', 'Tante Dian', NULL),
    ('Bpk. Achmad Setiadi & Istri', 'bpk-achmad-setiadi-istri', 'Tante Dian', NULL),
    ('Bpk. Ilham Setiabudi & Istri', 'bpk-ilham-setiabudi-istri', 'Tante Dian', NULL),
    ('Keluarga (Alm) Bpk. Endang Waskita', 'keluarga-alm-bpk-endang-waskita', 'Tante Dian', NULL),
    ('Ibu Yeni', 'ibu-yeni', 'Tante Dian', NULL),
    ('Ibu Kinah', 'ibu-kinah', 'Tante Dian', NULL),
    ('Bpk. Agus Hartono & Istri', 'bpk-agus-hartono-istri', 'Tante Dian', NULL),
    ('Ibu Tutun Jumiati & Suami', 'ibu-tutun-jumiati-suami', 'Tante Dian', NULL),
    ('Bpk. Yusuf Permana & Istri', 'bpk-yusuf-permana-istri', 'Tante Dian', NULL),
    ('Bpk. Ichlas & Istri', 'bpk-ichlas-istri', 'Tante Dian', NULL),
    ('Bpk. Amirul Yusuf & Istri', 'bpk-amirul-yusuf-istri', 'Tante Dian', NULL),
    ('Bpk. Ivan Ekancono & Istri', 'bpk-ivan-ekancono-istri', 'Tante Dian', NULL),
    ('Bpk. Endang Kosasih & Istri', 'bpk-endang-kosasih-istri', 'Tante Dian', NULL),
    ('Bpk. Fajri & Istri', 'bpk-fajri-istri', 'Tante Dian', NULL),
    ('Bpk. Anas Luthfi & Istri', 'bpk-anas-luthfi-istri', 'Tante Dian', NULL),
    ('Bpk. Yasir Arafat', 'bpk-yasir-arafat', 'Tante Dian', NULL),
    ('Mazaya & Partner', 'mazaya-partner', 'Tante Dian', NULL),
    ('Bpk. Fauzi Buldan Y & Istri', 'bpk-fauzi-buldan-y-istri', 'Tante Dian', NULL),
    ('Ibu Christine', 'ibu-christine', 'Tante Dian', NULL),
    ('Bpk. Ariastiadi Saleh H & Istri', 'bpk-ariastiadi-saleh-h-istri', 'Tante Dian', NULL),
    ('Bpk. Hari Supada & Istri', 'bpk-hari-supada-istri', 'Tante Dian', NULL),
    ('Ibu Endah Yuliastini & Suami', 'ibu-endah-yuliastini-suami', 'Tante Dian', NULL),
    ('Diana & Suami', 'diana-suami', 'Tante Dian', NULL),
    ('Bpk. Ansari Siman & Istri', 'bpk-ansari-siman-istri', 'Tante Dian', NULL),
    ('Ibu Nurhayati', 'ibu-nurhayati', 'Tante Dian', NULL),
    ('Ibu Novi Hediyani & Suami', 'ibu-novi-hediyani-suami', 'Tante Dian', NULL),
    ('Alun Riawati & Suami', 'alun-riawati-suami', 'Tante Dian', NULL),
    ('Winne & Suami', 'winne-suami', 'Tante Dian', NULL),
    ('Mona Delviana & Suami', 'mona-delviana-suami', 'Tante Dian', NULL),
    ('Doni Novari & Suami', 'doni-novari-suami', 'Tante Dian', NULL),
    ('Wiwiek Darmansyah & Suami', 'wiwiek-darmansyah-suami', 'Tante Dian', NULL),
    ('Mieke Retno & Suami', 'mieke-retno-suami', 'Tante Dian', NULL),
    ('Seradesy & Suami', 'seradesy-suami', 'Tante Dian', NULL),
    ('Dian Purwandari & Suami', 'dian-purwandari-suami', 'Tante Dian', NULL),
    ('Yurida & Suami', 'yurida-suami', 'Tante Dian', NULL),
    ('Berry Waworuntu & Suami', 'berry-waworuntu-suami', 'Tante Dian', NULL)
) AS v(name, slug, source, phone)
WHERE NOT EXISTS (
    SELECT 1 FROM guests g WHERE g.slug = v.slug
);
